version: '3.8'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5410:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - 6310:6379
    volumes:
      - redis_data:/data

  api:
    build: .
    command: npm run api start
    environment:
      NODE_ENV: staging
      PORT: 5000
      API_URL: http://localhost/api/v1
      CLIENT_URL: http://localhost
      PG_HOST: postgres
      PG_PORT: 5432
      REDIS_URL: redis://redis:6379
    restart: on-failure
    depends_on:
      - postgres
      - redis

  web:
    build: .
    command: npm run web serve
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api/v1
    restart: on-failure
    depends_on:
      - api

  nginx:
    image: nginx:latest
    environment:
      WEB_PORT: 3000
      API_PORT: 5000
    ports:
      - 80:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates/
    restart: on-failure
    depends_on:
      - api
      - web

volumes:
  postgres_data:
  redis_data:
