export enum AuthFailureReason {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
}

export enum GeoLookupFailureReason {
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND'
}
