export const neededItems = [
  'Cereal',
  'Soup',
  'Pasta',
  'Rice',
  'Tinned tomatoes',
  'Pasta sauce',
  'Lentils',
  'Beans/pulses',
  'Baked beans',
  'Spaghetti',
  'Tinned meat',
  'Tinned peas',
  'Tinned sweetcorn',
  'Tinned carrots',
  'Tinned mixed veg',
  'Tinned potatoes',
  'Tea',
  'Coffee',
  'Tinned fruit',
  'Biscuits',
  'Milk (UHT)',
  'Fruit juice',
  'Crisps',
  'Sweets',
  'Chocolate',
  'Rice pudding',
  'Curry jar',
  'Tuna',
  'Sardines',
  'Packet noodles',
  'Microavable rice',
  'Custard',
  'Instant mashed potato',
  'Sugar',
  'Porridge',
  'Buscuits',
  'Ketchup',
  'Mayonnaise',
  'Peanut butter',
  'Bread',
  'Nappies',
  'Baby wipes',
  'Baby food',
  'Baby snacks',
  'Baby shampoo',
  'Baby bodywash',
  'Womens deodorant',
  'Mens deodorant',
  'Razors',
  'Toilet roll',
  'Shampoo',
  'Soap',
  'Toothpaste',
  'Toothbrush',
  'Shower gel',
  'Shaving gel',
  'Hand wipes',
  'Hand sanitiser',
  'Sanitary pads',
  'Tampons',
  'Washing up liquid',
  'Laundry detergent',
  'Laundry powder',
  'Fabric softener'
];
