export enum UserRole {
  ADMIN = 'ADMIN',
  BENEFICIARY = 'BENEFICIARY'
}

export enum CharityUserRole {
  ADMIN = 'ADMIN',
  VOLUNTEER = 'VOLUNTEER'
}

export enum ListState {
  CREATED = 'CREATED',
  PROCESSING = 'PROCESSING',
  FULFILLED = 'FULFILLED',
  PARTLY_FULFILLED = 'PARTLY_FULFILLED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED'
}
